const newNovels = [
{ title: "Cronos Tale of the dark adventurer", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "Recently Updated", chapters: "58", collections: "4", url: "https://www.webnovel.com/book/cronos-tale-of-the-dark-adventurer_27541424406057005" },
{ title: "The Witch In Love With The Enigmatic Butler", author: "EimonQ", genre: "Fantasy, REINCARNATION, R18, COMEDY, MAGIC, TRAGEDY, GENIUS, POSSESSIVE, ROYALFAMILY, ABANDONED, FAKEIDENTITY", rating: "0", addtags: "Recently Updated", chapters: "83", collections: "58", url: "https://www.webnovel.com/book/the-witch-in-love-with-the-enigmatic-butler_29894016008028505" },
{ title: "A Doctor Who Just Wants to Paint", author: "EimonQ", genre: "Urban, R18, COMEDY, GENIUS, REVENGE, CEO, FIRSTLOVE, FAMILY, ABANDONED, ARRANGEDMARRIAGE, DOCTOR", rating: "0", addtags: "Recently Updated", chapters: "111", collections: "375", url: "https://www.webnovel.com/book/a-doctor-who-just-wants-to-paint_29497849700100405" },
{ title: "I Have the Sacred Sword", author: "EimonQ", genre: "Fantasy, ACTION, ADVENTURE, COMEDY, MAGIC, SUPERPOWERS, ANTIHERO, ABANDONED, LIGHTNOVEL, THESTRONGACTINGWEAK, SHAPESHIFTER", rating: "0", addtags: "none", chapters: "38", collections: "22", url: "https://www.webnovel.com/book/i-have-the-sacred-sword_30085019700546205" },
{ title: "I Have the Most Powerful Rank XXX Weapons!", author: "EimonQ", genre: "Fantasy, R18, WEAKTOSTRONG, HAREM, ANTIHERO, LEVELUP, LIGHTNOVEL, ADVANCEDTECHNOLOGY, EGOIST", rating: "0", addtags: "none", chapters: "50", collections: "65", url: "https://www.webnovel.com/book/i-have-the-most-powerful-rank-xxx-weapons!_30368539706504305" },
{ title: "Is It An Order", author: "EimonQ", genre: "Fantasy, REINCARNATION, COMEDY, GENIUS, ANTIHERO, VAMPIRE, ACADEMY, LIGHTNOVEL, THESTRONGACTINGWEAK, EGOIST, WIZARDS", rating: "0", addtags: "none", chapters: "33", collections: "22", url: "https://www.webnovel.com/book/is-it-an-order_30085077508713205" },

];

const oldNovels = [
{ title: "Cronos Tale of the dark adventurer", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "Recently Updated", chapters: "52", collections: "4", url: "https://www.webnovel.com/book/cronos-tale-of-the-dark-adventurer_27541424406057005" },
{ title: "A Doctor Who Just Wants to Paint", author: "EimonQ", genre: "Urban, R18, COMEDY, GENIUS, REVENGE, CEO, FIRSTLOVE, FAMILY, ABANDONED, ARRANGEDMARRIAGE, DOCTOR", rating: "0", addtags: "Recently Updated", chapters: "109", collections: "367", url: "https://www.webnovel.com/book/a-doctor-who-just-wants-to-paint_29497849700100405" },
{ title: "I Have the Most Powerful Rank XXX Weapons!", author: "EimonQ", genre: "Fantasy, R18, WEAKTOSTRONG, HAREM, ANTIHERO, LEVELUP, LIGHTNOVEL, ADVANCEDTECHNOLOGY, EGOIST", rating: "0", addtags: "Recently Updated", chapters: "44", collections: "61", url: "https://www.webnovel.com/book/i-have-the-most-powerful-rank-xxx-weapons!_30368539706504305" },
{ title: "I Have the Sacred Sword", author: "EimonQ", genre: "Fantasy, ACTION, ADVENTURE, COMEDY, MAGIC, SUPERPOWERS, ANTIHERO, ABANDONED, LIGHTNOVEL, THESTRONGACTINGWEAK, SHAPESHIFTER", rating: "0", addtags: "none", chapters: "35", collections: "23", url: "https://www.webnovel.com/book/i-have-the-sacred-sword_30085019700546205" },
{ title: "Is It An Order", author: "EimonQ", genre: "Fantasy, REINCARNATION, COMEDY, GENIUS, ANTIHERO, VAMPIRE, ACADEMY, LIGHTNOVEL, THESTRONGACTINGWEAK, EGOIST, WIZARDS", rating: "0", addtags: "none", chapters: "33", collections: "22", url: "https://www.webnovel.com/book/is-it-an-order_30085077508713205" },
{ title: "The Witch In Love With The Enigmatic Butler", author: "EimonQ", genre: "Fantasy, R18, COMEDY, DARK, TRAGEDY, POSSESSIVE, DRAMATIC, ABANDONED, SEDUCTIVE, BADBOY, FAKEIDENTITY", rating: "0", addtags: "none", chapters: "9", collections: "6", url: "https://www.webnovel.com/book/the-witch-in-love-with-the-enigmatic-butler_29894016008028505" },
];