const newNovels = [
                { title: "The Witch In Love With The Enigmatic Butler", cover: "../novels/covers/The Witch In Love With The Enigmatic Butler.webp", author: "EimonQ", chapters: "9", views: "7.9", rating: "0", synopsis: "Clare is a young woman who was abandoned by her parents as a child, becoming a maid for a noble family who subjected her to an abusive contract. Over the years, one day the mansion where she worked was attacked by a gang of criminals who set fire to the entire place. Luckily, someone manages to save Clare at the last moment, confronting and killing one of the criminals who was threatening her. Now she finds herself without a job and with almost no knowledge of the outside world. In this difficult situation, the person who saved her offers her a new job, but to take it they must travel to a city Clare has never heard of. What new job now awaits Clare?", url: "https://www.webnovel.com/book/the-witch-in-love-with-the-enigmatic-butler_29894016008028505" },
                { title: "Is It An Order", cover: "../novels/covers/Is It An Order.webp", author: "EimonQ", chapters: "30", views: "8.6", rating: "0", synopsis: "96 was a consciousness on the path to becoming the ultimate artificial intelligence, but since that didn't interest her, she was eliminated. To her surprise, she reincarnated in another world as the daughter of a vampire queen. Now she must compete for the throne while dealing with all the problems that a succession entails.", url: "https://www.webnovel.com/book/is-it-an-order_30085077508713205" },
                { title: "I Have the Sacred Sword", cover: "../novels/covers/I Have the Sacred Sword.webp", author: "EimonQ", chapters: "32", views: "6.8", rating: "0", synopsis: "Eleonora is an ego-sword that one day was abandoned by her candidate. Confident, she thought that not many days would pass until she would get a new owner, but to her surprise more than 3000 years passed. In her absence, too many things in the world changed. Most of the things she knows, work differently and magic, along with technology, are moving across the continent as the 3 great kingdoms compete. How will the sword adapt to this strange time never seen before?", url: "https://www.webnovel.com/book/i-have-the-sacred-sword_30085019700546205" },
                { title: "A Doctor Who Just Wants to Paint", cover: "../novels/covers/A Doctor Who Just Wants to Paint.webp", author: "EimonQ", chapters: "108", views: "115.7", rating: "0", synopsis: "Sheila Barker is a child prodigy who was sent away by her family to a foreign country after her mother's death. Years later, the Barker family calls Sheila back because they have arranged a marriage for her with the Long family, one of the most powerful in the country. On her return journey, Sheila meets a strange man who, for some reason, ends up greatly influencing her stay in that country. How will Sheila face this arranged marriage while seeking to end her relationship with her family once and for all? Author's Note: This story slightly incorporates special abilities with fantasy elements. Every place name, medical term, and jargon used within the context of the work is mostly fictitious.", url: "https://www.webnovel.com/book/a-doctor-who-just-wants-to-paint_29497849700100405" },
                { title: "I Have the Most Powerful Rank XXX Weapons!", cover: "../novels/covers/I Have the Most Powerful Rank XXX Weapons!.webp", author: "EimonQ", chapters: "25", views: "12.5", rating: "0", synopsis: "Leonar is a compulsive gambler with a special ability who, after an accident, ends up finding a legendary weapon of a rank never seen before. Becoming the owner of this weapon, and in turn, a highly sought-after target by his country, Leonar seeks to regain his peaceful life. 'Why aren't you dead?' 'What?' 'Oh... you have her. Damn it, break the contract, I don't want to work...'", url: "https://www.webnovel.com/book/i-have-the-most-powerful-rank-xxx-weapons!_30368539706504305" },
                { title: "Cronos Tale of the dark adventurer", cover: "../novels/covers/Cronos Tale of the dark adventurer.webp", author: "Axoth", chapters: "49", views: "10.4", rating: "0", synopsis: "Hayato Endou es un joven con delirios de grandeza que siempre ha soñado con seguir el camino del aventurero. Cuando el gremio acepta su petición para ser oficialmente aventurero. Él trata de adaptarse junto a sus amigos a su nuevo estilo de vida lleno de peligros y angustia.", url: "https://www.webnovel.com/book/cronos-tale-of-the-dark-adventurer_27541424406057005" },

];

const oldNovels = [
                { title: "The Witch In Love With The Enigmatic Butler", cover: "../novels/covers/The Witch In Love With The Enigmatic Butler.webp", author: "EimonQ", chapters: "9", views: "7", rating: "0", synopsis: "Clare is a young woman who was abandoned by her parents as a child, becoming a maid for a noble family who subjected her to an abusive contract. Over the years, one day the mansion where she worked was attacked by a gang of criminals who set fire to the entire place. Luckily, someone manages to save Clare at the last moment, confronting and killing one of the criminals who was threatening her. Now she finds herself without a job and with almost no knowledge of the outside world. In this difficult situation, the person who saved her offers her a new job, but to take it they must travel to a city Clare has never heard of. What new job now awaits Clare?", url: "https://www.webnovel.com/book/the-witch-in-love-with-the-enigmatic-butler_29894016008028505" },
                { title: "Is It An Order", cover: "../novels/covers/Is It An Order.webp", author: "EimonQ", chapters: "22", views: "5", rating: "0", synopsis: "96 was a consciousness on the path to becoming the ultimate artificial intelligence, but since that didn't interest her, she was eliminated. To her surprise, she reincarnated in another world as the daughter of a vampire queen. Now she must compete for the throne while dealing with all the problems that a succession entails.", url: "https://www.webnovel.com/book/is-it-an-order_30085077508713205" },
                { title: "I Have the Sacred Sword", cover: "../novels/covers/I Have the Sacred Sword.webp", author: "EimonQ", chapters: "23", views: "4", rating: "0", synopsis: "Eleonora is an ego-sword that one day was abandoned by her candidate. Confident, she thought that not many days would pass until she would get a new owner, but to her surprise more than 3000 years passed. In her absence, too many things in the world changed. Most of the things she knows, work differently and magic, along with technology, are moving across the continent as the 3 great kingdoms compete. How will the sword adapt to this strange time never seen before?", url: "https://www.webnovel.com/book/i-have-the-sacred-sword_30085019700546205" },
                { title: "A Doctor Who Just Wants to Paint", cover: "../novels/covers/A Doctor Who Just Wants to Paint.webp", author: "EimonQ", chapters: "80", views: "76", rating: "0", synopsis: "Sheila Barker is a child prodigy who was sent away by her family to a foreign country after her mother's death. Years later, the Barker family calls Sheila back because they have arranged a marriage for her with the Long family, one of the most powerful in the country. On her return journey, Sheila meets a strange man who, for some reason, ends up greatly influencing her stay in that country. How will Sheila face this arranged marriage while seeking to end her relationship with her family once and for all?", url: "https://www.webnovel.com/book/a-doctor-who-just-wants-to-paint_29497849700100405" },
];