const newNovels = [
                { title: "Cronos: Tale of the dark adventurer", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "Recently Updated", chapters: "50", collections: "2", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Burst: The Inhuman War", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", sinopsis: "Sin aviso todo aquello que ha amado fue arrebatado de la vida de Burst Ashtorn, primero fue su familia, luego su maestro, viéndose envuelto en un mundo cruel, sin tener conocimiento de lo que está pasando, ¿podrá abrirse paso a un nuevo destino?, ¿podrá superar la maldición que lo agobia? Solo el tiempo lo dirá.", chapters: "9", collections: "1", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Stardust hero's", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", chapters: "2", collections: "1", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Cronos: this cruel and realistic travel", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", chapters: "17", collections: "5", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "I Have the Most Powerful Rank XXX Weapons!", author: "EimonQ", genre: "Fantasy, R18, WEAKTOSTRONG, HAREM, ANTIHERO, LEVELUP, LIGHTNOVEL, ADVANCEDTECHNOLOGY, EGOIST", rating: "0", addtags: "Recently Updated", chapters: "38", collections: "56", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "A Doctor Who Just Wants to Paint", author: "EimonQ", genre: "Urban, R18, COMEDY, GENIUS, REVENGE, CEO, FIRSTLOVE, FAMILY, ABANDONED, ARRANGEDMARRIAGE, DOCTOR", rating: "0", addtags: "none", chapters: "108", collections: "363", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "I Have the Sacred Sword?", author: "EimonQ", genre: "Fantasy, ACTION, ADVENTURE, COMEDY, MAGIC, SUPERPOWERS, ANTIHERO, ABANDONED, LIGHTNOVEL, THESTRONGACTINGWEAK, SHAPESHIFTER", rating: "0", addtags: "none", chapters: "32", collections: "22", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "Is It An Order?", author: "EimonQ", genre: "Fantasy, REINCARNATION, COMEDY, GENIUS, ANTIHERO, VAMPIRE, ACADEMY, LIGHTNOVEL, THESTRONGACTINGWEAK, EGOIST, WIZARDS", rating: "0", addtags: "none", chapters: "30", collections: "21", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "The Witch In Love With The Enigmatic Butler", author: "EimonQ", genre: "Fantasy, R18, COMEDY, DARK, TRAGEDY, POSSESSIVE, DRAMATIC, ABANDONED, SEDUCTIVE, BADBOY, FAKEIDENTITY", rating: "0", addtags: "none", chapters: "9", collections: "6", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "Shadow Slave", author: "Guiltythree", genre: "Fantasy, ACTION, ROMANCE, ADVENTURE, SYSTEM, MAGIC, WEAKTOSTRONG, SUPERPOWERS, TRANSMIGRATION, ANTIHERO, THESTRONGACTINGWEAK", rating: "4.68", addtags: "Hot, Recently Updated", chapters: "1850", collections: "389800", url: "https://www.webnovel.com/profile/4316552864" },
{ title: "Free Fall (Pyramid of Gold)", author: "Guiltythree", genre: "Sci-fi, ACTION, ROMANCE, DARK, SUPERPOWERS, SLICEOFLIFE, SURVIVAL, EVOLUTION, SCARY, URBAN, THESTRONGACTINGWEAK", rating: "4.87", addtags: "none", chapters: "62", collections: "5300", url: "https://www.webnovel.com/profile/4316552864" },
];

const oldNovels = [
{ title: "Cronos: Tale of the dark adventurer", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "Recently Updated", chapters: "50", collections: "2", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Burst: The Inhuman War", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", sinopsis: "Sin aviso todo aquello que ha amado fue arrebatado de la vida de Burst Ashtorn, primero fue su familia, luego su maestro, viéndose envuelto en un mundo cruel, sin tener conocimiento de lo que está pasando, ¿podrá abrirse paso a un nuevo destino?, ¿podrá superar la maldición que lo agobia? Solo el tiempo lo dirá.", chapters: "9", collections: "1", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Stardust hero's", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", chapters: "2", collections: "1", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "Cronos: this cruel and realistic travel", author: "Mazhira", genre: "Fantasy", rating: "0", addtags: "none", chapters: "17", collections: "5", url: "https://www.webnovel.com/profile/4320923922" },
{ title: "I Have the Most Powerful Rank XXX Weapons!", author: "EimonQ", genre: "Fantasy, R18, WEAKTOSTRONG, HAREM, ANTIHERO, LEVELUP, LIGHTNOVEL, ADVANCEDTECHNOLOGY, EGOIST", rating: "0", addtags: "Recently Updated", chapters: "38", collections: "56", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "A Doctor Who Just Wants to Paint", author: "EimonQ", genre: "Urban, R18, COMEDY, GENIUS, REVENGE, CEO, FIRSTLOVE, FAMILY, ABANDONED, ARRANGEDMARRIAGE, DOCTOR", rating: "0", addtags: "none", chapters: "108", collections: "363", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "I Have the Sacred Sword?", author: "EimonQ", genre: "Fantasy, ACTION, ADVENTURE, COMEDY, MAGIC, SUPERPOWERS, ANTIHERO, ABANDONED, LIGHTNOVEL, THESTRONGACTINGWEAK, SHAPESHIFTER", rating: "0", addtags: "none", chapters: "32", collections: "22", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "Is It An Order?", author: "EimonQ", genre: "Fantasy, REINCARNATION, COMEDY, GENIUS, ANTIHERO, VAMPIRE, ACADEMY, LIGHTNOVEL, THESTRONGACTINGWEAK, EGOIST, WIZARDS", rating: "0", addtags: "none", chapters: "30", collections: "21", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "The Witch In Love With The Enigmatic Butler", author: "EimonQ", genre: "Fantasy, R18, COMEDY, DARK, TRAGEDY, POSSESSIVE, DRAMATIC, ABANDONED, SEDUCTIVE, BADBOY, FAKEIDENTITY", rating: "0", addtags: "none", chapters: "9", collections: "6", url: "https://www.webnovel.com/profile/4327668708" },
{ title: "Shadow Slave", author: "Guiltythree", genre: "Fantasy, ACTION, ROMANCE, ADVENTURE, SYSTEM, MAGIC, WEAKTOSTRONG, SUPERPOWERS, TRANSMIGRATION, ANTIHERO, THESTRONGACTINGWEAK", rating: "4.68", addtags: "Hot, Recently Updated", chapters: "1850", collections: "389800", url: "https://www.webnovel.com/profile/4316552864" },
{ title: "Free Fall (Pyramid of Gold)", author: "Guiltythree", genre: "Sci-fi, ACTION, ROMANCE, DARK, SUPERPOWERS, SLICEOFLIFE, SURVIVAL, EVOLUTION, SCARY, URBAN, THESTRONGACTINGWEAK", rating: "4.87", addtags: "none", chapters: "62", collections: "5300", url: "https://www.webnovel.com/profile/4316552864" },
];